# Generated by Django 2.2.1 on 2019-05-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='date_joined',
            new_name='date_employed',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='number_of_subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
    ]
